#import "@preview/grape-suite:3.1.0": exercise
#import "@preview/lilaq:0.6.0" as lq
#import "@preview/frame-it:2.0.0": *
#import "@preview/lovelace:0.3.1": *
#import exercise: project, subtask, task
#set page(numbering: "1")
#set heading(numbering: "1.")
#set math.equation(numbering: "(1)")

#let (example, feature, variant, syntax) = frames(
  feature: ("Feature", eastern),
  // For each frame kind, you have to provide its supplement title to be displayed
  variant: ("Variant", olive),
  // You can provide a color or leave it out and it will be generated
  example: ("Example", gray),

  syntax: ("Syntax",),
)
// This is necessary. Don't forget this!
#show: frame-style(styles.boxy)

#set text(lang: "en")

#show: project.with(
  title: "Homework 8",

  university: [Centro de Investigación en Matemáticas],
  institute: [Maestría en Ciencias de la Computación],
  semester: "Semester 2",
  abstract: none,
  author: "Pedro D. Llerenas",
)


#feature[Exercise 1][3D data set fitting with linear least squares][
  Polynomials in two variables are functions $f:RR^n -> RR$ consisting of the
  sum of terms of the form $b x^n_1 x_2^m$, where $b in RR$ is called a
  coefficient. The degree of each term $b x_1^n x_2^m$ is the sum of the
  exponents $n + m$, and the degree of the polynomials is the largest degree
  among all the terms of the polynomial. Examples:

  $
    x_1^2 x_2 - 6 x_1^3 x_2^(12) + 10 x_1^2 - 7 x_2 + 1 & quad "degree " 15 \
          x_1^3 x_2^2 - x_1^3 x_2^(3) - x_1 x_2 + x_2^4 & quad "degree " 6 \
  $

  THe aim of this exercise is to implement a 3D data set fitting method using a polynomial regression by minimizing the linear least squares
  $
    arg min_(b in RR^p) norm(y - X beta)^2
  $ 
  where the vector $beta$ contains the coefficients of the polynomial.

  1. Determine $p$ in $(0,1)$ in the function of the degree of the polynomial.
  2. Write a Python function that, given a degree, returns the corresponding matrix $X$ 
  3. Using the matrix $X$ constructed in 2, compute the solution of the
     minimization problem for polynomials of degree 1, 3, 4, 5, 6, 7. For each
    degree, plot the surface generated by the polynomial, plot the dataset and
    the true function as well, to show the polynomial adjusts to the data and the
    true function.
  4. Compute the mean square error of each polynomial with respect to both the
     dataset and the true funciton. Which polynomial best approximates the true
    function?
]

#example[Solution][
  
]



