#import "@preview/grape-suite:3.1.0": exercise
#import "@preview/lilaq:0.6.0" as lq
#import "@preview/frame-it:2.0.0": *
#import "@preview/lovelace:0.3.1": *
#import exercise: project, subtask, task
#set page(numbering: "1")
#set heading(numbering: "1.")
#set math.equation(numbering: "(1)")
#let (example, feature, variant, syntax) = frames(
  feature: ("Feature", eastern),
  // For each frame kind, you have to provide its supplement title to be displayed
  variant: ("Variant", olive),
  // You can provide a color or leave it out and it will be generated
  example: ("Example", gray),

  syntax: ("Syntax",),
)
// This is necessary. Don't forget this!
#show: frame-style(styles.thmbox)

#set text(lang: "en")

#show: project.with(
  title: "Homework 8",

  university: [Centro de Investigación en Matemáticas],
  institute: [Maestría en Ciencias de la Computación],
  semester: "Semester 2",
  abstract: none,
  author: "Pedro D. Llerenas",
)


#feature[Exercise 1][3D data set fitting with linear least squares][
  Polynomials in two variables are functions $f:RR^n -> RR$ consisting of the
  sum of terms of the form $b x^n_1 x_2^m$, where $b in RR$ is called a
  coefficient. The degree of each term $b x_1^n x_2^m$ is the sum of the
  exponents $n + m$, and the degree of the polynomials is the largest degree
  among all the terms of the polynomial. Examples:

  $
    x_1^2 x_2 - 6 x_1^3 x_2^(12) + 10 x_1^2 - 7 x_2 + 1 & quad "degree " 15 \
          x_1^3 x_2^2 - x_1^3 x_2^(3) - x_1 x_2 + x_2^4 & quad "degree " 6 \
  $

  The aim of this exercise is to implement a 3D data set fitting method using a polynomial regression by minimizing the linear least squares
  $
    arg min_(b in RR^p) norm(y - X beta)^2
  $<eq:min>
  where the vector $beta$ contains the coefficients of the polynomial.

  1. Determine $p$ in @eq:min in function of the degree of the polynomial.
  2. Write a Python function that, given a degree, returns the corresponding matrix $X$
  3. Using the matrix $X$ constructed in 2, compute the solution of the
    minimization problem for polynomials of degree 1, 3, 4, 5, 6, 7. For each
    degree, plot the surface generated by the polynomial, plot the dataset and
    the true function as well, to show the polynomial adjusts to the data and the
    true function.
  4. Compute the mean square error of each polynomial with respect to both the
    dataset and the true function. Which polynomial best approximates the true
    function?
]

*Solution.*
1. Given that we are only considering polynomials of degree 2, we only need to check for terms $x_1^n x_2^m$ in which $n+m = k$ for each $k = 0, 1, ..., d$. That is,
$
  "deg 0" & : x_1^0 x_2^0                       &  -> 1 \
  "deg 1" & : x_1^1, x_2^1                      &  -> 2 \
  "deg 2" & : x_1^2, x_1^1 x_2^1, x_2^2         &  -> 3 \
          & dots.v                              &       \
  "deg d" & : x_1^d, x_1^(d-1) x_2^1,..., x_2^d & ->d+1 \
$
Thus, we have
$
  p = sum_(i = 1)^(d+1) i = ((d+1)(d+2))/2.
$
2. Using part 1, we build the matrix
$
  X = mat(
    1, x_1, x_1^2, ..., x_1^p;
    1, x_2, x_2^2, ..., x_2^p;
    dots.v, dots.v, dots.v, ..., dots.v;
    1, x_n, x_n^2, ..., x_n^p
  )
$
That is,
$
  X = mat(
    1, x_1, x_1^2, ..., x_1^p;
    1, x_2, x_2^2, ..., x_2^p;
  )
$
where $p = ((d+1)(d+2))/2$. See `p1.py` for the implementation.

3. Running `python p1.py` will plot the corresponding functions.
4. Running `python p1.py` and comparing all the MSE's with the true function, we find that the polynomial of degree 3 is the best fit.

#grid(
  ```
  Degree   | MSE (Dataset / Noisy)     | MSE (True Function)
  -----------------------------------------------------------------
  1        | 0.10986                   | 0.06151
  3        | 0.05866                   | 0.02206
  4        | 0.05797                   | 0.02238
  5        | 0.05580                   | 0.02293
  6        | 0.05383                   | 0.02313
  7        | 0.04908                   | 0.02391
  -----------------------------------------------------------------
  The polynomial that best approximates the true function is Degree 3.
  ```,
)
#grid(
  columns: (1fr, 1fr),
  figure(
    image("deg1.jpg"),
  ),
  figure(
    image("deg3.jpg"),
  ),

  figure(
    image("deg4.jpg"),
  ),
  figure(
    image("deg5.jpg"),
  ),

  figure(
    image("deg6.jpg"),
  ),
  figure(
    image("deg7.jpg"),
  ),
)

#feature[Exercise 2][3D data set fitting with nonlinear least squares][
  Given the dataset ${(x_(1i), x_(2i), y_i)}$ of Exercise 1, and the aim of this exercise is to determine the coefficients $beta = (beta_0, beta_1, beta_2, beta_3)^top$ of the model
  $
    f(beta; x) = beta_0 + beta_1 sin (beta_2 x_1) cos (beta_3 x_2)
  $
  solving the nonlinear least squares problem
  $
    arg min_beta sum_(i = 1)^m r_i (beta)^2
  $
  where $r_i(beta) = f(beta; x_(1i), x_(2i)) - y_i$ are the components of the residual vector
  $
    r(beta) = vec(r_1(beta), r_2(beta), dots.v, r_m (beta))
  $
  1. write a python function that evaluates the model $f(beta;x)$.
  2. write a python function that evaluates the residual $r(beta)$ for the dataset of exercise 1.
  3. Write a python function that computes the value of the Jacobian of $r(beta)$, where the partial derivatives have been determined in an analytic manner.
  4. Write a python function that implements the Levenberg-Marquardt algorithm to solve the non-linear least squares problem.
  5. Test the algorithm with the following parameters:
  - Initial point $beta_0 = (1,1,0.75, 0.5)^top$
  - $mu_"ref" = 0.001$
  - Threshold $tau = sqrt(m)epsilon_m^(1/3)$, where $epsilon_m$ is the machine epsilon.
  - Maximum number of iterations $N = 200$.

    i. Print the final vector $beta_k$, the final value $f(x_k)$, the final number of iterations $k$ and the variable res that indicates whether the threshold has been reached before the end of the iterations.

    ii. Calculate the mean square error with respect to the dataset and the true function, and print the values.

    iii. Plot the surface generated by the model, plot the dataset and the true function as well, to show how the model adjusts to the data and the true function
  6. Repeat 5. with the following initial point $beta_0 = (1,0.5, 0.75, 0.5)^top$.
]

*Soltuion.*
Running `python p2.py` gives us the results of all the queries.
#figure(
  ```
  ==================================================
  Running Experiment 5
  Initial beta0: [1.   1.   0.75 0.5 ]
  ==================================================
  res = 1
  Iterations completed: 29
  Final fitted parameters (beta): [1.63090241e-02 1.00502138e+00 1.00353350e+00 4.45938984e-06]
  Final f(xk): 1.5624609656622717
  MSE (Model vs Dataset):         0.021701
  MSE (True Function vs Dataset): 0.021891

  ==================================================
  Running Experiment 6
  Initial beta0: [1.   0.5  0.75 0.5 ]
  ==================================================
  res = 1
  Iterations completed: 31
  Final fitted parameters (beta): [ 1.63090230e-02  1.00502138e+00  1.00353350e+00 -3.02084351e-06]
  Final f(xk): 1.5624609656525705
  MSE (Model vs Dataset):         0.021701
  MSE (True Function vs Dataset): 0.021891
  ```,
)
#grid(
  columns: 2,
  figure(
    image("5.jpg"),
  ),
  figure(
    image("6.jpg"),
  ),
)


#feature[Exercise 3][Constrained least-squares][
  Let $H in RR^(p times n)$ be a matrix of rank $n$, and the function $f:RR^n->RR$ defined by
  $
    f(x) = norm(y - H x)^2.
  $
  1. Let $C in RR^(q times n)$ and $b in RR^q$. Show that $f$ has a unique minimum on the set $S colon.eq {x in RR^n, C x = b}$.
  2. Assuming that $C$ is such that the matrix $C(H^top H)^(-1) C^top$ has rank $q$, determine the minimum of $f$ on $S$.
  3. Express the minimum of $f$ on $S$ in function of the minimum of $f$ on $RR^n$.
]

*Proof.*
1. As seen before in class, $f$ can be proven to be convex on $RR^n$. Taking
  into account that $H$ has full column rank, $f$ is strictly convex, thus if
  we prove $S$ is convex, we are done. To prove it, let $x,y in S$ and $alpha in
  [0,1]$, then
  $
    alpha C x + (1-alpha)C y = alpha b + (1-alpha) b = b.
  $
  Thus, $alpha C x + (1-alpha)C y in S$, so $S$ is convex, and thus $f$ has a unique minimum in $S$.
2. Expanding $f$, we have
  $
    (y - H x)^top (y - H x) = y^top y -2 y^top H x + x^top H^top H x
  $
  Thus, constraining to $x in S$, we obtain the Lagrangian
  $
    cal(L)(x, lambda) = y^top y -2 y^top H x + x^top H^top H x + 2 lambda (C x - b)
  $
  where we deliberately used $2 lambda$ for further simplifications. The gradient w.r.t. $x$ is given by
  $
    nabla_x cal(L)(x, lambda) = -2 y^top H + 2H^top H x + 2C^top lambda
  $
  Setting it equal to zero, we obtain
  $
    x = (H^top H)^(-1)(y^top H - C^top lambda).
  $
  Thus, substituting into the constraint equation, we have
  $
    C(H^top H)^(-1)y^top H - C(H^top H)^(-1)C^top lambda = b \
    <=> lambda =
    [C(H^top H)^(-1)C^top]^(-1)[C(H^top H)^(-1)y^top H - b],
  $
  where we used that $C(H^top H)^(-1)C^top$ has full column rank to invert it. Substituting back into $x$, we have
  $
    x = (H^top H)^(-1)y^top H - (H^top H)^(-1)C^top [C(H^top H)^(-1)C^top]^(-1)[C(H^top
        H)^(-1)y^top H - b]
  $<eq:constr>
3. Now, we find the minimum of $f$ in $RR^n$.
  $
    nabla f(x) equiv 0 & <=> -2y^top H + 2 H^top H x = 0 \
                       & <=> x^* = (H^top H)^(-1)y^top H
  $
  Thus, on @eq:constr, we may instead write
  $
    x = x^* - (H^top H)^(-1)C^top [C(H^top H)^(-1)C^top]^(-1)[C x^* - b].
  $
#align(right, [$qed$])

#feature[Exercise 4][Projection onto convex sets][
  Using KKT conditions, determine the projection operator onto:

  1. the closed ball of center $(0,0)$ and radius $R$.
  2. a closed box $[a_1, b_1] times [a_2, b_2]$, where $a_1 < b_1$ ad $a_2 < b_2$.
]
*Proof.*
We want to minimize the distance from a point $y$ and the set
$
  B_R = {x in RR^n: norm(x) <= R}.
$
That is,
$
  min_x 1/2 norm(x - y)^2, quad x in B_R.
$
Equivalently,
$
  min_(x in RR^n) 1/2 norm(x - y)^2, " constrained to " norm(x)^2 -R^2 <= 0.
$
The associated Lagrangian is thus
$
  cal(L)(x, mu) = 1/2 norm(x-y)^2 + mu (norm(x)^2 - R^2).
$
The KKT conditions are:
$
  & nabla_x cal(L)(x, mu) = (x-y) + 2mu x = 0, \
  & norm(x)^2 <= R^2, \
  & mu >= 0, \
  & mu(norm(x)^2 - R^2) = 0.
$
The first condition gives
$
  x = 1/(1+2mu) y.
$
We consider the inactive case of the constraint ($mu = 0$), which gives
$
  x = y,
$
and thus the second condition becomes
$
  norm(y) <= R,
$
so the projection is itself. If it is active ($mu > 0$), the last condition implies
$
  norm(x) = R,
$
and thus the first equation, after taking the norm, becomes
$
  norm(x) = 1/(1+2mu) norm(y) = R <=> 1/(1+2mu) = R/norm(y),
$
and thus
$
  x = R y / norm(y).
$
Thus, we conclude that the projection function onto the closed ball is
$
  pi_(B_R)(y) = cases(y & "if " norm(y) <= R, R y/norm(y) & "if " norm(y) > R).
$

2. Similar to the previous solution, we want to minimize
$
  min_x 1/2 (x_1 - y_1)^2 + 1/2 (x_2 - y_2)^2, quad (x_1, x_2) in {(x_1, x_2) in RR^2 : a_1 <= x_1 <= b_1, a_2 <= x_2 <= b_2 }
$
The constraints may be written as
$
  x_1 - b_1 <= 0\
  x_2 - b_2 <= 0\
  a_1 - x_1 <= 0\
  a_2 - x_2 <= 0
$
Since these inequalities are independent of each other (for each component), and we may also separate the objective function as a sum of independent functions, thus we may simplify the analysis of the Lagrangian to a component-wise analysis. That is,
$
  cal(L) (x_1, lambda, mu) = 1/2(x_1 - y_1)^2 + lambda(x_1-b_1) + mu(x_1 - a_1)\
  cal(L) (x_2, lambda, mu) = 1/2(x_2 - y_1)^2 + lambda(x_2-b_2) + mu(x_2 - a_2).
$
And therefore,
$
  nabla_(x_i) cal(L) (x_i, lambda, mu) = (x_i - y_i) + lambda - mu\
$<eq:stationary>
- If $y_i in [a_i, b_i]$, setting $mu = lambda = 0$, we obtain $x_i = y_i$ and
  thus $x_i$ satisfies the conditions.
- If $y_i > b_i$, assume the upper bound is active, so $x_i = b_i$, and the
  lower is not, so that $mu = 0$. @eq:stationary then gives $lambda = y_i - b_i >
  0$, satisfying the condition, so $x_i = b_i$.
- If $y_i < a_i$, assume the lower bound is active, so $x_i = a_i$ and the upper
  is inactive, so $lambda = 0$.
  @eq:stationary gives $mu = a_i - y_i > 0$, satisfying the condition, so $x_i = a_i$.
Therefore, the projection operator is given by
$
  pi_([a_1,b_1] times [a_2, b_2])(y_1, y_2) &= cases(y_i & "if " y_i in [a_i, b_i], a_i & "if " y_i < a_i, b_i & "if " y_i > b_i) = vec(min(max(y_1, a_1), b_1), min(max(y_2, a_2), b_2))
$
#align(right, [$qed$])
