#import "@preview/grape-suite:3.1.0": exercise
#import "@preview/lilaq:0.6.0" as lq
#import "@preview/frame-it:2.0.0": *
#import exercise: project, subtask, task
#set page(numbering: "1")
#set heading(numbering: "1.")
#set math.equation(numbering: "(1)")

#let (example, feature, variant, syntax) = frames(
  feature: ("Feature",),
  // For each frame kind, you have to provide its supplement title to be displayed
  variant: ("Variant",),
  // You can provide a color or leave it out and it will be generated
  example: ("Example", gray),

  syntax: ("Syntax",),
)
// This is necessary. Don't forget this!
#show: frame-style(styles.boxy)

#set text(lang: "en")

#show: project.with(
  title: "Homework 6",

  university: [Centro de Investigación en Matemáticas],
  institute: [Maestría en Ciencias de la Computación],
  show-outline: true,

  author: "Pedro D. Llerenas",

  show-solutions: false,
)

#feature[Exercise 1][Conjugate Gradient][
  Implement the Algorithm 5.2 (conjugated gradient) in the book Numerical
  Optimization of Nocedal and Wright to solve the system
  $
    A x = b
  $<eq:1>
  where $A in RR^(n times n)$ such that $A^top = A$ and $A succ 0$, $b in RR^n$

  Apply the system to solve a system of equations: such as
  - $A$ given in the file `M_sys125x125.txt`,
  - $b$ given in the file `V_sys125x1.txt`,
  using a preconditioner different from the Identity.
]
We use the Jacobi preconditioner, which consists in taking the diagonal
elements of $A$, and forming a diagonal matrix $hat(A)$ with these elements. This
matrix is easy to invert, so solving $hat(A) A x = hat(A) b$ is cheap.

To execute the program, use

#figure(
  ```sh
    julia --project=. p1.jl M_sys_125x125.txt V_sys_125x1.txt
  ```,
)
This will print the number of iterations needed for convergence, and the solution vector.

#feature[Exercise 2][Application to image processing][
  1. *Implementation of basic operators*: In a `Python` script, write the following functions:
    - `forward_derivative_x`: which
      implements the forward differences with
      respect to the first variable of a 2D
      function.
    - `forward_derivative_y`: which
      implements the forward differences with
      respect to the second variable of a 2D
      function.
    - `backward_derivative_x`: which
      implements the backward differences with
      respect to the first variable of a 2D
      function.
    - `backward_derivative_y`: which
      implements the backward differences with
      respect to the second variable of a 2D
      function.
  Set the values of the function to zero where they are not
  well-defined (it occurs at the boundary of the domain).

  From these operators define:
  - a function `gradient` which constructs the gradient of a 2D
    function using forward derivatives.
  - a function `divergence` which constructs the divergence operator of a 2D
    vector field using backward derivatives.

  2. *Image denoising*. Let $u_0$ be a grey-level image of
    size $M times N$. A standard model to remove the noise
    in $u_0$ consists of minimizing the function
  $
    E(u) = sum_(x = 0)^(M - 1) sum_(y=0)^(N-1) 1/2 (u(x,y) - u_0(x,y))^2 + gamma sqrt(norm(nabla u(x,y))^2+epsilon)
  $<eq:2>
  where $gamma, epsilon > 0$.

  The gradient of the function $E$ at $u$ is
  $
    nabla E(u) = u - u_0 + gamma "div"((nabla u)/(sqrt(norm(nabla u)^2 + epsilon)))
  $
  *Task*: Implement the gradient descent algorithm to
  minimize @eq:2 where:
  - the image $u_0$ is `noisy2y_kodim23_greylevel.png`,
  - the initial condition of the gradient descent is $u_0$,
  - the step size $alpha$ of the gradient descent is $0.0001$,
  - the number of iterations is 15000,
  - $gamma = 40$,
  - $eta = 0.0001$.
]

To execute the program, use

#figure(
  ```sh
    julia --project=. p2.jl
  ```,
)
This will initiate the gradient descent algorithm, and after some time, will save the
output denoised image. The following are some examples.

#grid(
  columns: (1fr, 1fr),
  gutter: 1em,
  figure(
    image("noisy25_kodim23_greylevel.png"),
    caption: [Noisy image.],
  ),
  figure(
    image("denoised_result.png"),
    caption: [Denoised with $gamma = 40$. ],
  ),

  figure(
    image("denoised_result_2.png"),
    caption: [Denoised with $gamma = 10$. ],
  ),
  figure(
    image("denoised_result_1.png"),
    caption: [Denoised with $gamma = 0.1$. ],
  ),
)

We observe that $gamma$ correctly applies a greater blur to the image when its
magnitude increases.

#feature[Exercise 3][Newton's method][
  Let $f in C^2(RR^n)$, and $g = f circle.small A$, where $A in RR^(n times n)$  is invertible. Let us consider the sequence ${x_k}$ generated by Newton's method to minimize $f$ and ${y_k}$ the sequence generated by Newton's method to minimize $g$, and where $x_0 = A y_0$.

  1. Establish a relation between the sequences ${x_k}$ and ${y_k}$.
  2. Conclude.
]

1. Newton's method generates a sequence for minimizing $f(x)$ given by
$
  x_(k+1) = x_k - [nabla^2 f(x_k)]^(-1)nabla f(x_k)
$
The sequence for minimizing $g(y)$ is given by
$
  y_(k+1) = y_k - [nabla^2 g(y_k)]^(-1)nabla g(y_k)
$
By the Chain Rule, one has
$
  nabla g(y) = A^top nabla f(A y)
$
and
$
  nabla^2 g(y) = A^top nabla^2 f(A y) A.
$
Therefore, we have
$
  y_(k+1) & = y_k - [A^top nabla^2 f(A y_k) A]^(-1)A^top nabla f(A y_k) \
          & = y_k - A^(-1) nabla^2 f(A y_k)^(-1) (A^top)^(-1)A^top nabla f(A y_k) \
          & = y_k - A^(-1) nabla^2 f(A y_k)^(-1) nabla f(A y_k)
$
Multiplying by $A$ on both sides yields
$
  A y_(k+1) & = A y_k - nabla^2 f(A y_k)^(-1) nabla f(A y_k)
$
We will prove by induction that $x_k = A y_k$. The base case is given ($x_0 = A
y_0$), thus we assume it to be true for $k$. Then, one has, by substituting
$x_k = A y_k$ into the formula for $k + 1$,
$
  A y_(k+1) & = x_k - nabla^2 f(x_k)^(-1) nabla f(x_k) = x_(k+1).
$
This proves the induction hypothesis.

2. We conclude that Newton's method is affine invariant. The sequence of points
  remains physicially identical to the original space.

#feature[Exercise 4][Coercivity][
  1. Are the following functions coercive? Justify your answer.
  $
    f_1(x_1, x_2) = x_1^2 - 2 x_1 x_2 + x_2^2, quad f_2(x_1, x_2) = x_1^4 + x_2^4 - 3x_1 x_2
  $
  2. Let us consider the function $f:RR^n -> RR$  given by
  $
    f(x) = norm(J x - y)^2 + alpha norm(x)^2, quad alpha in RR,
  $
  where $J in RR^(n times n)$ and $y in RR^n$. Under which conditions on $J$ and $alpha$ is $f$ coercive?
]

1. To see that $f_1$ is *not* coercive, we take $x_1 = x_2$, and note that in this direction,
$
  lim_(abs(x_1) -> infinity) f_1(x_1,x_1) = lim_(abs(x_1) -> infinity) 0 = 0 eq.not infinity.
$
To prove that $f_2$ is coercive, we show that the lower bound of $f_2$ approaches infinity
when the norm of the input approaches infinity. First, we see that
$
  (x_1^2 - x_2^2)^2 >= 0 & <=> x_1^4 + x_2^4 >= 2x_1^2 x_2^2 \
                         & <=> 2(x_1^4 + x_2^4) >= (x_1^2 + x_2^2)^2 = norm(x)^4
$
Now, by the AM-GM inequality,
$
  abs(x_1 x_2) <= 1/2 (x_1^2 + x_2^2) = 1/2 norm(x)^2.
$
Therefore,
$
  -3 x_1 x_2 >= -3 abs(x_1 x_2) >= -3/2 (x_1^2 + x_2^2) = -3/2 norm(x)^2
$
We may then bound $f_2$:
$
  f_2(x_1,x_2) >= 1/2 norm(x)^4 - 3/2 norm(x)^2
$
Taking the limit as $norm(x) -> infinity$, the 4th order term dominates the 2nd
degree term. Therefore, at infinity, $f_2$ is bounded below by $infinity$, proving the
assertion.


2. We expand the expression:
$
  f(x) & = (J x - y)^top (J x - y) + alpha x^top x \
       & = x^top J^top J x - 2 y^top J x + y^top y + alpha x^top x \
       & = x^top (J^top J +alpha I)x - 2y^top J x + norm(y)^2
$
By @lemma:coercive, we must have $J^top J + alpha I succ 0$. Therefore, if
$alpha > 0$, any $J$ guarantees coerciveness. For $alpha = 0$, we need
$
  lambda_min (J^top J) > 0,
$
and for $alpha < 0$, we need
$
  lambda_min (J^top J) > alpha,
$
and $ker(J) = {0}$.

#variant[Lemma][
  The function $f(x) = x^top A x + b x + c$ is coercive if and only if $A succ 0$.
]<lemma:coercive>

*Proof.* ($<=$) Let $lambda_min$ be the minimum eigenvalue of $A$. By hypothesis, $A succ 0$, so
$lambda_min > 0$. Using Rayleigh's quotient for symmetric matrices, we have a lower bound
$
  x^top A x >= lambda_min norm(x)^2.
$
By Cauchy-Schwartz, one has
$
  b^top x >= - norm(b) norm(x).
$
Therefore,
$
  f(x) >= lambda_min norm(x)^2 - norm(b) norm(x) + c.
$
Since $lambda_min > 0$ and the dominance of the quadratic term, the function is
bounded below by $infinity$ when $norm(x) -> infinity$.

($=>$) By contrapositive, assume $A$ is not strictly positive definite, then by
symmetry of $A$, its eigenvalues are real. Therefore, it must be that at least
one $lambda <= 0$. Let $v in S^n$ be the associated eigenvector, then for
$x = t v$, with $t in RR_+$ one has
$
  lim_(t->infinity) f(t v) & = lim_(t->infinity)t^2 v^top A v + t b^top v + c \
                           & = lim_(t->infinity)t^2 lambda norm(v)^2 + t b^top v + c \
                           & = lim_(t->infinity)t^2 lambda + t b^top v + c.
$
In the case $lambda < 0$, the limit goes to $-infinity$. If $lambda = 0$, then
either $b^top v <= 0$ or $b^top v > 0$. In the former, the limit goes to
$-infinity$. In the latter, we change $t$ with $-t$, so we end up with the
previous case. This proves the statement.
#{
  align(right, [$square$ ])
}
