#include <iostream>
#include <vector>
#include <string>
#include <sstream>

using namespace std;

const int MAXN = 10000000;

// Packed bitset: 1 bit per integer. 1 = Self Number, 0 = Generated Number.
uint32_t is_self_block[MAXN / 32 + 5];

// Stores the prefix sum of self numbers at the START of each 32-bit block.
int prefix_counts[MAXN / 32 + 5];

void precompute() {
    // Initialize array with 1s (0xFF). We assume every number is a Self Number initially.
    for (int i = 0; i <= MAXN / 32; i++) {
        is_self_block[i] = 0xFFFFFFFFu;
    }

    // 0 is technically out of our logical range, unset its bit so it doesn't skew queries
    is_self_block[0] &= ~1u;

    int current_sod = 1;
    for (int i = 1; i <= MAXN; ++i) {
        int gen = i + current_sod;
        
        // If 'gen' is generated by 'i', knock out its Self Number status bit
        if (gen <= MAXN) {
            is_self_block[gen / 32] &= ~(1u << (gen % 32));
        }

        // Amortized O(1) sum-of-digits progression
        if ((i + 1) % 10 != 0) {
            current_sod++;
        } else {
            int temp = i + 1;
            int s = 0;
            while (temp) {
                s += temp % 10;
                temp /= 10;
            }
            current_sod = s;
        }
    }

    // Build the sparse prefix sum array
    int current_prefix = 0;
    for (int i = 0; i <= MAXN / 32; ++i) {
        prefix_counts[i] = current_prefix;
        current_prefix += __builtin_popcount(is_self_block[i]);
    }
}

// O(1) query using sparse prefix sum and bit-masking
int count_self(int x) {
    if (x <= 0) return 0;
    if (x > MAXN) x = MAXN;
    
    int block = x / 32;
    int ans = prefix_counts[block];
    
    int rem = x % 32;
    
    // Mask out bits strictly above 'rem'. 
    // Handled safely to avoid undefined behavior if rem == 31.
    uint32_t mask = (rem == 31) ? 0xFFFFFFFFu : ((1u << (rem + 1)) - 1);
    
    ans += __builtin_popcount(is_self_block[block] & mask);
    return ans;
}

// O(1) query. The maximum sum of digits for N <= 10^7 is 63 (for 9999999).
// Therefore, the generator must lie exactly in the range [a - 63, a).
int fun1(int a) {
    // reject if self flagged as self number
    if ((is_self_block[a / 32] & (1u << (a % 32))) != 0) {
        return -1;
    }
    
    // We scan ascendingly to guarantee we return the smallest generator
    int start = max(1, a - 90); 
    for (int i = start; i < a; ++i) {
        int temp = i;
        int s = i;
        while (temp) {
            s += temp % 10;
            temp /= 10;
        }
        if (s == a) return i;
    }
    return -1;
}

void solve() {
    precompute();
    
    string line;
    
    int t = 0;
    stringstream ss(line);
    ss >> t;
    
    for (int case_num = 1; case_num <= t; ++case_num) {
        if (!getline(cin, line)) break;
        
        if (!line.empty() && line.back() == '\r') {
            line.pop_back();
        }
        
        if (line.empty() || line.find_first_not_of(" \t") == string::npos) {
            case_num--; 
            continue;
        }
        
        stringstream ss_line(line);
        int a = -1, b = -1;
        ss_line >> a;
        
        if (ss_line >> b) {
            // function Overload 1: Two parameters
            int ans = 0;
            if (a <= b) {
                ans = count_self(b) - count_self(a - 1);
            }
            cout << "Case " << case_num << ": " << ans << '\n';
        } else {
            // function Overload 2
            cout << "Case " << case_num << ": " << fun1(a) << '\n';
        }
    }
}

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    solve();

    return 0;
}